# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Server build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Standalone Binaries
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build server
      run: cd server && go build -v

    - name: Upload server binary
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ws-server
        path: server/server
        retention-days: 12
        overwrite: true

    - name: Build client wrapper
      run: cd client-v2-wrapper && go build -v

    - name: Upload client wrapper
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ws-client-v2-wrapper
        path: client-v2-wrapper/client-v2-wrapper
        retention-days: 12
        overwrite: true

  push_to_registry:
    name: Build Server Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: masteraler/wsn
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
