# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Server build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: cd server && go build -v 

    - name: Upload
      uses: actions/upload-artifact@v4.4.3
      with:
        name: wsn-server
        path: server/server
        retention-days: 1
        overwrite: true
